[package]
name = "kzg10"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bls12-381 = "0.3"
ark-ec = "0.3"
ark-ff = "0.3"
ark-std = "0.3"
bls12_381 = "0.6"
ff = "0.11"
group = "0.11"
rand = "0.8"
